#include "api.hpp"
#include <sys/socket.h>
#include <netinet/in.h>
#include <unistd.h>
#include <sstream>
#include <cstring>
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <regex>
#include <cctype>
#include <cerrno>
namespace fs=std::filesystem;
namespace piai::api {
Server::~Server(){stop();}
Response Server::json(int s,const std::string&b){return{s,"application/json",b};}
std::string Server::reason(int s){switch(s){case 200:return"OK";case 201:return"Created";case 400:return"Bad Request";case 404:return"Not Found";case 405:return"Method Not Allowed";case 409:return"Conflict";case 413:return"Payload Too Large";case 500:return"Internal Server Error";case 501:return"Not Implemented";default:return"Error";}}
std::string Server::url_path(const std::string&p){auto q=p.find('?');return q==std::string::npos?p:p.substr(0,q);}
static bool valid_utf8(const std::string&s,size_t&i){unsigned char c=(unsigned char)s[i];size_t n=s.size();if(c<0x80){i++;return true;}if(c>=0xC2&&c<=0xDF){if(i+1<n&&(s[i+1]&0xC0)==0x80){i+=2;return true;}return false;}if(c>=0xE0&&c<=0xEF){if(i+2>=n)return false;unsigned char b=(unsigned char)s[i+1],d=(unsigned char)s[i+2];if((b&0xC0)!=0x80||(d&0xC0)!=0x80)return false;if(c==0xE0&&b<0xA0)return false;if(c==0xED&&b>=0xA0)return false;i+=3;return true;}if(c>=0xF0&&c<=0xF4){if(i+3>=n)return false;unsigned char b=(unsigned char)s[i+1],d=(unsigned char)s[i+2],e=(unsigned char)s[i+3];if((b&0xC0)!=0x80||(d&0xC0)!=0x80||(e&0xC0)!=0x80)return false;if(c==0xF0&&b<0x90)return false;if(c==0xF4&&b>=0x90)return false;i+=4;return true;}return false;}
static std::string clean_text(const std::string&s){std::string o;o.reserve(s.size());for(size_t i=0;i<s.size();){size_t old=i;if(!valid_utf8(s,i)){o+="\xEF\xBF\xBD";i=old+1;continue;}unsigned char c=(unsigned char)s[old];if(c<0x20&&c!='\n'&&c!='\r'&&c!='\t')continue;if(c==0x7F)continue;o.append(s,old,i-old);}return o;}
std::string Server::json_escape(const std::string&s){std::string o;std::string clean=clean_text(s);for(unsigned char c:clean){if(c=='"'||c=='\\'){o+='\\';o+=(char)c;}else if(c=='\n')o+="\\n";else if(c=='\r')o+="\\r";else if(c=='\t')o+="\\t";else if(c<0x20)o+=' ';else o+=(char)c;}return o;}
bool Server::listen(uint16_t port){if(running_)return true;port_=port;fd_=socket(AF_INET,SOCK_STREAM,0);if(fd_<0)return false;int one=1;setsockopt(fd_,SOL_SOCKET,SO_REUSEADDR,&one,sizeof(one));sockaddr_in a{};a.sin_family=AF_INET;a.sin_addr.s_addr=htonl(INADDR_ANY);a.sin_port=htons(port_);if(bind(fd_,(sockaddr*)&a,sizeof(a))<0||::listen(fd_,16)<0){stop();return false;}try{fs::create_directories(storage_);}catch(...){stop();return false;}running_=true;return true;}
void Server::stop(){if(fd_>=0)::close(fd_);fd_=-1;running_=false;}
Response Server::load_model(const std::string&name){if(name.empty()||name.find('/')!=std::string::npos||name.find('\\')!=std::string::npos)return json(400,"{\"error\":\"invalid_model_name\"}");fs::path p=fs::path(storage_)/name;if(!fs::is_regular_file(p)||p.extension()!=".gguf")return json(404,"{\"error\":\"model_not_found\"}");auto m=std::make_unique<gguf::Model>();if(!m->open(p.string()))return json(400,"{\"error\":\"invalid_or_unsupported_gguf\"}");auto e=std::make_unique<inference::Engine>();if(!e->load(*m))return json(400,"{\"error\":\"model_architecture_or_tensors_unsupported\"}");loaded_name_=name;engine_=std::move(e);model_=std::move(m);const auto&a=engine_->architecture();std::ostringstream b;b<<"{\"name\":\""<<json_escape(name)<<"\",\"loaded\":true,\"architecture\":\""<<json_escape(a.name)<<"\",\"layers\":"<<a.layers<<",\"hidden\":"<<a.hidden<<",\"heads\":"<<a.heads<<",\"kv_heads\":"<<a.kv_heads<<",\"vocab\":"<<a.vocab<<",\"context\":"<<a.context<<"}";return json(200,b.str());}
Response Server::generate(const Request&r,const std::string&name){if(!engine_||!model_||loaded_name_!=name)return json(409,"{\"error\":\"model_not_loaded\"}");std::string prompt;size_t max_tokens=32;std::smatch m;if(std::regex_search(r.body,m,std::regex("\\\"prompt\\\"\\s*:\\s*\\\"([^\\\"]*)\\\"")))prompt=m[1].str();else return json(400,"{\"error\":\"prompt_required\"}");if(std::regex_search(r.body,m,std::regex("\\\"max_tokens\\\"\\s*:\\s*(\\d+)"))){try{max_tokens=std::stoull(m[1].str());}catch(...){return json(400,"{\"error\":\"invalid_max_tokens\"}");}}if(max_tokens==0||max_tokens>4096)return json(400,"{\"error\":\"max_tokens_out_of_range\"}");std::vector<std::string>tokens;if(!engine_->generate(prompt,max_tokens,tokens))return json(500,"{\"error\":\"inference_failed\"}");std::string text;for(const auto&t:tokens)text+=t;return json(200,"{\"model\":\""+json_escape(name)+"\",\"text\":\""+json_escape(text)+"\",\"tokens\":"+std::to_string(tokens.size())+"}");}
Response Server::route(const Request&r){std::string p=url_path(r.path);
 if(r.method=="GET"&&p=="/api/v1/health")return json(200,"{\"status\":\"ok\",\"runtime\":\"piai\"}");
 if(r.method=="GET"&&p=="/api/v1/models"){std::string b="{\"models\":[";bool first=true;try{for(auto&e:fs::directory_iterator(storage_)){if(!e.is_regular_file()||e.path().extension()!=".gguf")continue;if(!first)b+=',';first=false;std::string n=e.path().filename().string();b+="{\"name\":\""+json_escape(n)+"\",\"loaded\":"+(loaded_name_==n&&engine_?"true":"false")+"}";}}catch(...){}b+="]}";return json(200,b);}
 if(r.method=="POST"&&p=="/api/v1/models/upload"){
   auto ct=r.headers.find("content-type");if(ct==r.headers.end())return json(400,"{\"error\":\"missing_content_type\"}");auto bp=ct->second.find("boundary=");if(bp==std::string::npos)return json(400,"{\"error\":\"multipart_required\"}");std::string boundary="--"+ct->second.substr(bp+9);auto hpos=r.body.find(boundary);if(hpos==std::string::npos)return json(400,"{\"error\":\"invalid_multipart\"}");auto hs=r.body.find("\r\n\r\n",hpos);if(hs==std::string::npos)return json(400,"{\"error\":\"invalid_multipart\"}");hs+=4;auto end=r.body.find("\r\n"+boundary,hs);if(end==std::string::npos)return json(400,"{\"error\":\"invalid_multipart\"}");std::string h=r.body.substr(hpos,hs-hpos);std::smatch m;if(!std::regex_search(h,m,std::regex("filename=\\\"([^\\\"]+)\\\"")))return json(400,"{\"error\":\"missing_filename\"}");std::string name=m[1].str();for(char&c:name)if(!(std::isalnum((unsigned char)c)||c=='.'||c=='-'||c=='_'))c='_';if(name.size()<5||name.substr(name.size()-5)!=".gguf")return json(400,"{\"error\":\"gguf_required\"}");fs::path out=fs::path(storage_)/name,tmp=out;tmp+=".uploading";std::ofstream f(tmp,std::ios::binary|std::ios::trunc);if(!f)return json(500,"{\"error\":\"storage_error\"}");f.write(r.body.data()+hs,(std::streamsize)(end-hs));if(!f){f.close();fs::remove(tmp);return json(500,"{\"error\":\"write_failed\"}");}f.close();std::error_code ec;fs::rename(tmp,out,ec);if(ec){fs::remove(tmp);return json(500,"{\"error\":\"rename_failed\"}");}return json(201,"{\"name\":\""+json_escape(name)+"\",\"stored\":true,\"loaded\":false}");}
 const std::string pre="/api/v1/models/";if(r.method=="POST"&&p.rfind(pre,0)==0){std::string rest=p.substr(pre.size());auto slash=rest.find('/');if(slash==std::string::npos)return json(404,"{\"error\":\"not_found\"}");std::string name=rest.substr(0,slash),action=rest.substr(slash+1);if(action=="load")return load_model(name);if(action=="generate")return generate(r,name);}
 return json(404,"{\"error\":\"not_found\"}");}
void Server::serve_once(){if(!running_)return;int c=accept(fd_,nullptr,nullptr);if(c<0)return;std::string raw;char buf[65536];size_t content_length=0;bool headers_done=false;for(;;){ssize_t n=recv(c,buf,sizeof(buf),0);if(n<=0)break;raw.append(buf,(size_t)n);if(!headers_done){auto he=raw.find("\r\n\r\n");if(he!=std::string::npos){headers_done=true;auto cl=raw.find("Content-Length:");if(cl!=std::string::npos){auto e=raw.find("\r\n",cl);try{content_length=std::stoull(raw.substr(cl+15,e-cl-15));}catch(...){content_length=0;}}}}if(headers_done&&raw.size()-(raw.find("\r\n\r\n")+4)>=content_length)break;if(raw.size()>512ull*1024*1024){::close(c);return;}}
auto he=raw.find("\r\n\r\n");if(he==std::string::npos){::close(c);return;}std::istringstream in(raw.substr(0,he));Request r;in>>r.method>>r.path;std::string line;std::getline(in,line);while(std::getline(in,line)&&line!="\r"){if(!line.empty()&&line.back()=='\r')line.pop_back();auto x=line.find(':');if(x!=std::string::npos){std::string k=line.substr(0,x),v=line.substr(x+1);while(!v.empty()&&v[0]==' ')v.erase(v.begin());std::transform(k.begin(),k.end(),k.begin(),[](unsigned char x){return std::tolower(x);});r.headers[k]=v;}}r.body=raw.substr(he+4);Response out=route(r);std::string h="HTTP/1.1 "+std::to_string(out.status)+" "+reason(out.status)+"\r\nContent-Type: "+out.content_type+"\r\nContent-Length: "+std::to_string(out.body.size())+"\r\nConnection: close\r\n\r\n"+out.body;send(c,h.data(),h.size(),MSG_NOSIGNAL);::close(c);}
void Server::serve_forever(){while(running_)serve_once();}
}
