#include "gguf.hpp"
#include <cstring>
#include <fcntl.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <unistd.h>
namespace piai::gguf {
static bool rd(const uint8_t*&p,const uint8_t*e,void*d,size_t n){if(!p||p>e||n>(size_t)(e-p))return false;if(n&&d)std::memcpy(d,p,n);p+=n;return true;}
template<class T> static bool r(const uint8_t*&p,const uint8_t*e,T&v){return rd(p,e,&v,sizeof v);}
static bool value(const uint8_t*&p,const uint8_t*e,Type t,Value&v){v=Value{};v.type=t;switch(t){case Type::UINT8:case Type::INT8:case Type::BOOL:v.bytes.resize(1);return rd(p,e,v.bytes.data(),1);case Type::UINT16:case Type::INT16:v.bytes.resize(2);return rd(p,e,v.bytes.data(),2);case Type::UINT32:case Type::INT32:case Type::FLOAT32:v.bytes.resize(4);return rd(p,e,v.bytes.data(),4);case Type::UINT64:case Type::INT64:case Type::FLOAT64:v.bytes.resize(8);return rd(p,e,v.bytes.data(),8);case Type::STRING:{uint64_t n;if(!r(p,e,n)||n>(1ull<<26)||n>(uint64_t)(e-p))return false;v.string.assign((const char*)p,(size_t)n);p+=n;return true;}case Type::ARRAY:{uint32_t at;uint64_t n;if(!r(p,e,at)||at>12||!r(p,e,n)||n>(1ull<<24))return false;v.array.reserve((size_t)n);for(uint64_t i=0;i<n;i++){Value x;if(!value(p,e,(Type)at,x))return false;v.array.push_back(std::move(x));}return true;}default:return false;}}
Model::~Model(){close();}
void Model::close(){if(map_)munmap(map_,map_size_);map_=nullptr;if(fd_>=0)::close(fd_);fd_=-1;map_size_=data_offset_=version_=0;meta_.clear();tensors_.clear();}
bool Model::open(const std::string&path){close();fd_=::open(path.c_str(),O_RDONLY|O_CLOEXEC);if(fd_<0)return false;struct stat st{};if(fstat(fd_,&st)||st.st_size<24){close();return false;}map_size_=(size_t)st.st_size;map_=mmap(nullptr,map_size_,PROT_READ,MAP_PRIVATE,fd_,0);if(map_==MAP_FAILED){map_=nullptr;close();return false;}const uint8_t*p=(const uint8_t*)map_,*e=p+map_size_;char magic[4];uint64_t nt=0,nm=0;if(!rd(p,e,magic,4)||std::memcmp(magic,"GGUF",4)||!r(p,e,version_)||version_<1||version_>3||!r(p,e,nt)||!r(p,e,nm)||nt>1000000||nm>1000000){close();return false;}for(uint64_t i=0;i<nm;i++){uint64_t n;uint32_t ty;if(!r(p,e,n)||n>(1ull<<26)||n>(uint64_t)(e-p)){close();return false;}std::string k((const char*)p,(size_t)n);p+=n;if(!r(p,e,ty)||ty>12){close();return false;}Value v;if(!value(p,e,(Type)ty,v)){close();return false;}meta_[std::move(k)]=std::move(v);}for(uint64_t i=0;i<nt;i++){Tensor t;uint64_t n;uint32_t rank,ty;if(!r(p,e,n)||n>(1ull<<26)||n>(uint64_t)(e-p)){close();return false;}t.name.assign((const char*)p,(size_t)n);p+=n;if(!r(p,e,rank)||rank>64){close();return false;}t.shape.resize(rank);for(auto&d:t.shape)if(!r(p,e,d)){close();return false;}if(!r(p,e,ty)||!r(p,e,t.offset)){close();return false;}t.type=(TensorType)ty;tensors_.push_back(std::move(t));}uint64_t align=32;if(const Value*v=metadata("general.alignment");v&&v->type==Type::UINT32&&v->bytes.size()>=4)std::memcpy(&align,v->bytes.data(),4);if(!align||align>4096){close();return false;}uint64_t pos=(uint64_t)(p-(const uint8_t*)map_);data_offset_=(pos+align-1)/align*align;if(data_offset_>map_size_){close();return false;}for(auto&t:tensors_){uint64_t n=1;for(uint64_t d:t.shape){if(d&&n>UINT64_MAX/d){close();return false;}n*=d;}uint64_t b=0;switch(t.type){case TensorType::F32:b=n*4;break;case TensorType::F16:b=n*2;break;case TensorType::Q4_0:case TensorType::Q4_1:if(n%32){close();return false;}b=n/32*18;break;case TensorType::Q5_0:case TensorType::Q5_1:if(n%32){close();return false;}b=n/32*22;break;case TensorType::Q8_0:if(n%32){close();return false;}b=n/32*34;break;case TensorType::Q2_K:if(n%256){close();return false;}b=n/256*84;break;case TensorType::Q3_K:if(n%256){close();return false;}b=n/256*110;break;case TensorType::Q4_K:if(n%256){close();return false;}b=n/256*144;break;case TensorType::Q5_K:if(n%256){close();return false;}b=n/256*176;break;case TensorType::Q6_K:if(n%256){close();return false;}b=n/256*210;break;default:close();return false;}if(b>map_size_-data_offset_||t.offset>map_size_-data_offset_-b){close();return false;}t.size=b;}return true;}
const Value*Model::metadata(const std::string&k)const{auto i=meta_.find(k);return i==meta_.end()?nullptr:&i->second;}
const uint8_t*Model::data(const Tensor&t)const{return valid()&&t.offset<=map_size_-data_offset_&&t.size<=map_size_-data_offset_-t.offset?(const uint8_t*)map_+data_offset_+t.offset:nullptr;}
}
