#include "inference.hpp"
#include <cstring>
namespace piai::inference {
static bool f32(const gguf::Value*v,float&o){if(!v||v->bytes.size()<4)return false;std::memcpy(&o,v->bytes.data(),4);return true;}
bool Vocabulary::load(const gguf::Model&m){tokens_.clear();const auto*v=m.metadata("tokenizer.ggml.tokens");if(!v||!v->is_array())return false;const auto*s=m.metadata("tokenizer.ggml.scores");tokens_.reserve(v->array.size());for(size_t i=0;i<v->array.size();++i){if(!v->array[i].is_string())return false;Token t;t.text=v->array[i].string;if(s&&s->is_array()&&i<s->array.size())f32(&s->array[i],t.score);tokens_.push_back(std::move(t));}return !tokens_.empty();}
bool Vocabulary::encode(const std::string&s,std::vector<int32_t>&out)const{out.clear();if(tokens_.empty())return false;for(size_t p=0;p<s.size();){int best=-1;size_t bl=0;for(size_t i=0;i<tokens_.size();++i){const std::string&t=tokens_[i].text;if(t.size()<=bl||t.size()>s.size()-p)continue;if(std::memcmp(s.data()+p,t.data(),t.size())==0){best=(int)i;bl=t.size();}}if(best<0)return false;p+=bl;out.push_back(best);}return true;}
std::string Vocabulary::decode(int32_t id)const{return id>=0&&static_cast<size_t>(id)<tokens_.size()?tokens_[id].text:std::string{};}
bool KVCache::init(size_t l,size_t h,size_t d,size_t cap){if(!l||!h||!d||!cap||l>SIZE_MAX/(h*d)||l*h*d>SIZE_MAX/cap)return false;size_t n=l*h*d*cap;if(n>SIZE_MAX/(2*sizeof(float)))return false;k_.assign(n,0);v_.assign(n,0);layers_=l;heads_=h;head_dim_=d;capacity_=cap;used_=0;return true;}
void KVCache::clear(){used_=0;}
static TensorBinding bind(const gguf::Model&m,const std::string&n){for(const auto&t:m.tensors())if(t.name==n)return {&t,m.data(t)};return {};}
static TensorBinding either(const gguf::Model&m,const std::string&a,const std::string&b){auto x=bind(m,a);return x.tensor?x:bind(m,b);}
bool Engine::load(const gguf::Model&m){if(!detect_architecture(m,arch_)||!vocab_.load(m))return false;model_=&m;embedding_=either(m,"token_embd.weight","model.embed_tokens.weight");if(!embedding_.tensor)return false;q_.resize(arch_.layers);k_.resize(arch_.layers);v_.resize(arch_.layers);o_.resize(arch_.layers);norm1_.resize(arch_.layers);norm2_.resize(arch_.layers);ffn1_.resize(arch_.layers);ffn2_.resize(arch_.layers);ffn3_.resize(arch_.layers);for(size_t i=0;i<arch_.layers;i++){std::string n=std::to_string(i);q_[i]=either(m,"blk."+n+".attn_q.weight","model.layers."+n+".self_attn.q_proj.weight");k_[i]=either(m,"blk."+n+".attn_k.weight","model.layers."+n+".self_attn.k_proj.weight");v_[i]=either(m,"blk."+n+".attn_v.weight","model.layers."+n+".self_attn.v_proj.weight");o_[i]=either(m,"blk."+n+".attn_output.weight","model.layers."+n+".self_attn.o_proj.weight");norm1_[i]=either(m,"blk."+n+".attn_norm.weight","model.layers."+n+".input_layernorm.weight");norm2_[i]=either(m,"blk."+n+".ffn_norm.weight","model.layers."+n+".post_attention_layernorm.weight");ffn1_[i]=either(m,"blk."+n+".ffn_gate.weight","model.layers."+n+".mlp.gate_proj.weight");ffn2_[i]=either(m,"blk."+n+".ffn_down.weight","model.layers."+n+".mlp.down_proj.weight");ffn3_[i]=either(m,"blk."+n+".ffn_up.weight","model.layers."+n+".mlp.up_proj.weight");if(!q_[i].tensor||!k_[i].tensor||!v_[i].tensor||!o_[i].tensor||!norm1_[i].tensor||!norm2_[i].tensor||!ffn2_[i].tensor)return false;}return cache_.init(arch_.layers,arch_.kv_heads,arch_.hidden/arch_.heads,arch_.context);}
bool Engine::generate(const std::string&,size_t,std::vector<std::string>&out){out.clear();return false;}
}
