#include "inference.hpp"
#include <algorithm>
#include <cmath>
#include <cstring>
#include <limits>
#include <string>
namespace piai::inference {
static float hf(uint16_t h){uint32_t s=h>>15,e=(h>>10)&31,f=h&1023;if(!e)return(s?-1.f:1.f)*std::ldexp((float)f,-24);if(e==31)return f?NAN:(s?-INFINITY:INFINITY);return(s?-1.f:1.f)*std::ldexp(1.f+f/1024.f,(int)e-15);}
static bool sf(const gguf::Value*v,float&o){if(!v||v->type!=gguf::Type::FLOAT32||v->bytes.size()<4)return false;std::memcpy(&o,v->bytes.data(),4);return true;}
static bool u32v(const gguf::Value*v,uint32_t&o){if(!v||v->bytes.size()<4)return false;std::memcpy(&o,v->bytes.data(),4);return true;}
static TensorBinding find(const gguf::Model&m,const std::string&n){for(const auto&t:m.tensors())if(t.name==n)return{&t,m.data(t)};return{};}
static TensorBinding alt(const gguf::Model&m,const std::string&a,const std::string&b=""){auto x=find(m,a);return x.tensor?x:find(m,b);}
static float elem(const TensorBinding&t,size_t i){if(!t.tensor||!t.data)return 0;auto ty=t.tensor->type;if(ty==gguf::TensorType::F32){float x;std::memcpy(&x,t.data+i*4,4);return x;}if(ty==gguf::TensorType::F16){uint16_t x;std::memcpy(&x,t.data+i*2,2);return hf(x);}size_t b=i/32,j=i%32,bs=(ty==gguf::TensorType::Q8_0?34:(ty==gguf::TensorType::Q4_0||ty==gguf::TensorType::Q4_1?18:22));const uint8_t*p=t.data+b*bs;uint16_t dh;std::memcpy(&dh,p,2);float d=hf(dh);if(ty==gguf::TensorType::Q8_0)return d*(int8_t)p[2+j];if(ty==gguf::TensorType::Q4_0||ty==gguf::TensorType::Q4_1){uint16_t mh=0;if(ty==gguf::TensorType::Q4_1)std::memcpy(&mh,p+2,2);const uint8_t*q=p+(ty==gguf::TensorType::Q4_1?4:2);int z=(j&1)?q[j/2]>>4:q[j/2]&15;return ty==gguf::TensorType::Q4_1?d*z+hf(mh):d*(z-8);}uint32_t qh;std::memcpy(&qh,p+2,4);const uint8_t*q=p+6;int z=(j&1)?q[j/2]>>4:q[j/2]&15;z|=((qh>>j)&1)<<4;if(ty==gguf::TensorType::Q5_1){uint16_t mh;std::memcpy(&mh,p+2,2);return d*z+hf(mh);}return d*(z-16);}
static void mv(const TensorBinding&w,const float*x,float*y,size_t r,size_t c){for(size_t i=0;i<r;i++){double s=0;for(size_t j=0;j<c;j++)s+=(double)elem(w,i*c+j)*x[j];y[i]=(float)s;}}
static void rms(const TensorBinding&w,std::vector<float>&x,float eps){double s=0;for(float z:x)s+=(double)z*z;float k=1.f/std::sqrt((float)(s/x.size())+eps);for(size_t i=0;i<x.size();i++)x[i]*=k*elem(w,i);}
static void rope(float*x,size_t d,size_t pos,float theta){for(size_t i=0;i+1<d;i+=2){float a=pos*std::pow(theta,-2.f*(i/2.f)/d),c=std::cos(a),s=std::sin(a),u=x[i],v=x[i+1];x[i]=u*c-v*s;x[i+1]=u*s+v*c;}}
static int sample(const std::vector<float>&l,const std::vector<int32_t>&hist,Sampling s,std::mt19937_64&r){if(l.empty())return-1;std::vector<std::pair<float,int>>v;v.reserve(l.size());for(size_t i=0;i<l.size();i++){float z=l[i];if(s.repeat_penalty>1)for(auto h:hist)if(h==(int32_t)i){z=z<0?z*s.repeat_penalty:z/s.repeat_penalty;break;}v.push_back({z,(int)i});}if(s.temperature<=0)return std::max_element(v.begin(),v.end())->second;for(auto&a:v)a.first/=s.temperature;std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.first>b.first;});if(s.top_k>0&&v.size()>(size_t)s.top_k)v.resize(s.top_k);float mx=v[0].first,sum=0;for(auto&a:v){a.first=std::exp(a.first-mx);sum+=a.first;}for(auto&a:v)a.first/=sum;float acc=0;size_t n=v.size();for(size_t i=0;i<v.size();i++){acc+=v[i].first;if(acc>=s.top_p){n=i+1;break;}}std::uniform_real_distribution<float>u(0,1);float total=0;for(size_t i=0;i<n;i++)total+=v[i].first;float q=u(r)*total,c=0;for(size_t i=0;i<n;i++){c+=v[i].first;if(q<=c)return v[i].second;}return v[n-1].second;}
bool KVCache::init(size_t l,size_t h,size_t d,size_t cap){if(!l||!h||!d||!cap||l>SIZE_MAX/(h*d)||l*h*d>SIZE_MAX/cap)return false;size_t n=l*h*d*cap;if(n>SIZE_MAX/(2*sizeof(float)))return false;k_.assign(n,0);v_.assign(n,0);layers_=l;heads_=h;head_dim_=d;capacity_=cap;used_=0;return true;}
void KVCache::clear(){used_=0;std::fill(k_.begin(),k_.end(),0);std::fill(v_.begin(),v_.end(),0);}float*KVCache::key(size_t l,size_t p,size_t h){return k_.data()+((l*capacity_+p)*heads_+h)*head_dim_;}float*KVCache::value(size_t l,size_t p,size_t h){return v_.data()+((l*capacity_+p)*heads_+h)*head_dim_;}
bool Vocabulary::load(const gguf::Model&m){tokens_.clear();auto*v=m.metadata("tokenizer.ggml.tokens");if(!v||!v->is_array())return false;auto*s=m.metadata("tokenizer.ggml.scores");tokens_.reserve(v->array.size());for(size_t i=0;i<v->array.size();i++){if(!v->array[i].is_string())return false;Token t{v->array[i].string,0};if(s&&s->is_array()&&i<s->array.size())sf(&s->array[i],t.score);tokens_.push_back(std::move(t));}return!tokens_.empty();}
bool Vocabulary::encode(const std::string&s,std::vector<int32_t>&out)const{out.clear();std::vector<std::string>forms;forms.push_back(s);std::string gpt,sp;for(size_t i=0;i<s.size();){unsigned char c=s[i];if(c==' '){gpt+="\xC4\xA0";sp+="\xE2\x96\x81";i++;}else{gpt.push_back((char)c);sp.push_back((char)c);i++;}}forms.push_back(gpt);forms.push_back(sp);for(const auto&f:forms){std::vector<int32_t>tmp;bool ok=true;for(size_t p=0;p<f.size();){int best=-1;size_t n=0;for(size_t i=0;i<tokens_.size();i++){const auto&t=tokens_[i].text;if(t.empty()||t.size()<=n||t.size()>f.size()-p)continue;if(!std::memcmp(f.data()+p,t.data(),t.size())){best=(int)i;n=t.size();}}if(best<0){ok=false;break;}tmp.push_back(best);p+=n;}if(ok&&!tmp.empty()){out=std::move(tmp);return true;}}return false;}
std::string Vocabulary::decode(int32_t id)const{
 if(id<0||(size_t)id>=tokens_.size())return{};
 const std::string&s=tokens_[id].text;
 if(s.size()>=4&&s.front()=='<'&&s.back()=='>'){
  if(s.size()==6&&s[1]=='0'&&s[2]=='x'){
   auto hex=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return -1;};
   int a=hex(s[3]),b=hex(s[4]);if(a>=0&&b>=0)return std::string(1,(char)((a<<4)|b));
  }
  if(s.size()>=3&&s[1]=='|')return{};
 }
 std::string r;
 r.reserve(s.size());
 for(size_t i=0;i<s.size();){
  unsigned char c=(unsigned char)s[i];
  // GPT-2 byte-level BPE uses U+0120 (UTF-8 C4 A0) for a leading space.
  if(i+1<s.size()&&c==0xC4&&(unsigned char)s[i+1]==0xA0){r.push_back(' ');i+=2;continue;}
  // SentencePiece uses U+2581 (UTF-8 E2 96 81) for a leading space.
  if(i+2<s.size()&&c==0xE2&&(unsigned char)s[i+1]==0x96&&(unsigned char)s[i+2]==0x81){r.push_back(' ');i+=3;continue;}
  // Some exports contain the literal UTF-8 replacement/underscore forms.
  if(c=='_'&&i+1<s.size()&&s[i+1]==' '){r.push_back('_');i+=1;continue;}
  r.push_back((char)c);++i;
 }
 return r;
}
bool Engine::load(const gguf::Model&m){if(!detect_architecture(m,arch_)||!vocab_.load(m))return false;model_=&m;embedding_=alt(m,"token_embd.weight","model.embed_tokens.weight");output_=alt(m,"output.weight","lm_head.weight");if(!output_.tensor)output_=embedding_;norm_final_=alt(m,"output_norm.weight","model.norm.weight");if(!embedding_.tensor||!norm_final_.tensor)return false;size_t L=arch_.layers;q_.resize(L);k_.resize(L);v_.resize(L);o_.resize(L);norm1_.resize(L);norm2_.resize(L);ffn1_.resize(L);ffn2_.resize(L);ffn3_.resize(L);for(size_t i=0;i<L;i++){std::string n=std::to_string(i);q_[i]=alt(m,"blk."+n+".attn_q.weight","model.layers."+n+".self_attn.q_proj.weight");k_[i]=alt(m,"blk."+n+".attn_k.weight","model.layers."+n+".self_attn.k_proj.weight");v_[i]=alt(m,"blk."+n+".attn_v.weight","model.layers."+n+".self_attn.v_proj.weight");o_[i]=alt(m,"blk."+n+".attn_output.weight","model.layers."+n+".self_attn.o_proj.weight");norm1_[i]=alt(m,"blk."+n+".attn_norm.weight","model.layers."+n+".input_layernorm.weight");norm2_[i]=alt(m,"blk."+n+".ffn_norm.weight","model.layers."+n+".post_attention_layernorm.weight");ffn1_[i]=alt(m,"blk."+n+".ffn_gate.weight","model.layers."+n+".mlp.gate_proj.weight");ffn2_[i]=alt(m,"blk."+n+".ffn_down.weight","model.layers."+n+".mlp.down_proj.weight");ffn3_[i]=alt(m,"blk."+n+".ffn_up.weight","model.layers."+n+".mlp.up_proj.weight");if(!q_[i].tensor||!k_[i].tensor||!v_[i].tensor||!o_[i].tensor||!norm1_[i].tensor||!norm2_[i].tensor||!ffn1_[i].tensor||!ffn2_[i].tensor)return false;}return cache_.init(L,arch_.kv_heads,arch_.hidden/arch_.heads,arch_.context);}
bool Engine::generate(const std::string&prompt,size_t max_tokens,std::vector<std::string>&out){out.clear();if(!model_||!max_tokens)return false;std::vector<int32_t>ids;if(!vocab_.encode(prompt,ids)||ids.empty())return false;uint32_t bos=0;if(u32v(model_->metadata("tokenizer.ggml.bos_token_id"),bos)&&bos<vocab_.size())ids.insert(ids.begin(),(int32_t)bos);cache_.clear();size_t hd=arch_.hidden/arch_.heads;std::vector<float>x(arch_.hidden),z(arch_.hidden),q(arch_.hidden),kk(arch_.kv_heads*hd),vv(arch_.kv_heads*hd),a(arch_.hidden),logits(arch_.vocab);for(size_t pos=0;pos<ids.size()+max_tokens&&pos<arch_.context;pos++){int32_t id=ids[pos];if(id<0||(size_t)id>=vocab_.size())return false;for(size_t i=0;i<arch_.hidden;i++)x[i]=elem(embedding_,(size_t)id*arch_.hidden+i);for(size_t l=0;l<arch_.layers;l++){z=x;rms(norm1_[l],z,arch_.eps);mv(q_[l],z.data(),q.data(),arch_.hidden,arch_.hidden);mv(k_[l],z.data(),kk.data(),arch_.kv_heads*hd,arch_.hidden);mv(v_[l],z.data(),vv.data(),arch_.kv_heads*hd,arch_.hidden);for(size_t h=0;h<arch_.heads;h++)rope(q.data()+h*hd,hd,pos,arch_.rope_theta);for(size_t h=0;h<arch_.kv_heads;h++)rope(kk.data()+h*hd,hd,pos,arch_.rope_theta);for(size_t h=0;h<arch_.kv_heads;h++){std::memcpy(cache_.key(l,pos,h),kk.data()+h*hd,hd*4);std::memcpy(cache_.value(l,pos,h),vv.data()+h*hd,hd*4);}for(size_t h=0;h<arch_.heads;h++){size_t kh=h%arch_.kv_heads;std::vector<float>s(pos+1);float mx=-std::numeric_limits<float>::infinity();for(size_t p=0;p<=pos;p++){s[p]=0;for(size_t j=0;j<hd;j++)s[p]+=q[h*hd+j]*cache_.key(l,p,kh)[j];s[p]/=std::sqrt((float)hd);mx=std::max(mx,s[p]);}float sm=0;for(float&u:s){u=std::exp(u-mx);sm+=u;}for(float&u:s)u/=sm;for(size_t j=0;j<hd;j++){float u=0;for(size_t p=0;p<=pos;p++)u+=s[p]*cache_.value(l,p,kh)[j];a[h*hd+j]=u;}}mv(o_[l],a.data(),z.data(),arch_.hidden,arch_.hidden);for(size_t i=0;i<arch_.hidden;i++)x[i]+=z[i];z=x;rms(norm2_[l],z,arch_.eps);std::vector<float>g(arch_.intermediate),u(arch_.intermediate),d(arch_.hidden);mv(ffn1_[l],z.data(),g.data(),arch_.intermediate,arch_.hidden);if(ffn3_[l].tensor)mv(ffn3_[l],z.data(),u.data(),arch_.intermediate,arch_.hidden);else u=g;for(size_t i=0;i<g.size();i++){float t=g[i];float sig=1.f/(1.f+std::exp(-std::max(-80.f,std::min(80.f,t))));g[i]=(t*sig)*u[i];}mv(ffn2_[l],g.data(),d.data(),arch_.hidden,arch_.intermediate);for(size_t i=0;i<arch_.hidden;i++)x[i]+=d[i];}if(pos+1>=ids.size()){z=x;rms(norm_final_,z,arch_.eps);mv(output_,z.data(),logits.data(),arch_.vocab,arch_.hidden);int next=sample(logits,ids,sampling_,rng_);if(next<0)return false;ids.push_back(next);out.push_back(vocab_.decode(next));if(out.size()>=max_tokens)return true;}}return!out.empty();}
}