#include "inference.hpp"
#include <algorithm>
#include <array>
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <cstring>
#include <limits>
#include <mutex>
#include <string>
#include <thread>
#include <unordered_map>
#include <utility>
#include <vector>

namespace piai::inference {

static float hf(uint16_t h){uint32_t s=h>>15,e=(h>>10)&31,f=h&1023;if(!e)return(s?-1.f:1.f)*std::ldexp((float)f,-24);if(e==31)return f?NAN:(s?-INFINITY:INFINITY);return(s?-1.f:1.f)*std::ldexp(1.f+f/1024.f,(int)e-15);}
static bool sf(const gguf::Value*v,float&o){if(!v||v->type!=gguf::Type::FLOAT32||v->bytes.size()<4)return false;std::memcpy(&o,v->bytes.data(),4);return true;}
static bool u32v(const gguf::Value*v,uint32_t&o){if(!v||v->bytes.size()<4)return false;std::memcpy(&o,v->bytes.data(),4);return true;}
static bool bv(const gguf::Value*v,bool&o){if(!v||v->type!=gguf::Type::BOOL||v->bytes.empty())return false;o=v->bytes[0]!=0;return true;}
static TensorBinding find(const gguf::Model&m,const std::string&n){for(const auto&t:m.tensors())if(t.name==n)return{&t,m.data(t)};return{};}
static TensorBinding alt(const gguf::Model&m,const std::string&a,const std::string&b=""){auto x=find(m,a);return x.tensor?x:find(m,b);}
static float elem(const TensorBinding&t,size_t i){if(!t.tensor||!t.data)return 0;auto ty=t.tensor->type;if(ty==gguf::TensorType::F32){float x;std::memcpy(&x,t.data+i*4,4);return x;}if(ty==gguf::TensorType::F16){uint16_t x;std::memcpy(&x,t.data+i*2,2);return hf(x);}size_t b=i/32,j=i%32,bs=(ty==gguf::TensorType::Q8_0?34:(ty==gguf::TensorType::Q4_0||ty==gguf::TensorType::Q4_1?18:22));const uint8_t*p=t.data+b*bs;uint16_t dh;std::memcpy(&dh,p,2);float d=hf(dh);if(ty==gguf::TensorType::Q8_0)return d*(int8_t)p[2+j];if(ty==gguf::TensorType::Q4_0||ty==gguf::TensorType::Q4_1){uint16_t mh=0;if(ty==gguf::TensorType::Q4_1)std::memcpy(&mh,p+2,2);const uint8_t*q=p+(ty==gguf::TensorType::Q4_1?4:2);int z=(j&1)?q[j/2]>>4:q[j/2]&15;return ty==gguf::TensorType::Q4_1?d*z+hf(mh):d*(z-8);}uint32_t qh;std::memcpy(&qh,p+2,4);const uint8_t*q=p+6;int z=(j&1)?q[j/2]>>4:q[j/2]&15;z|=((qh>>j)&1)<<4;if(ty==gguf::TensorType::Q5_1){uint16_t mh;std::memcpy(&mh,p+2,2);return d*z+hf(mh);}return d*(z-16);}

// Persistent workers use every hardware thread reported by the CPU. Each worker
// claims independent output rows without launching threads per token.
class MVWorkers{std::vector<std::thread>workers_;std::mutex mu_;std::condition_variable cv_,done_;const TensorBinding*w_=nullptr;const float*x_=nullptr;float*y_=nullptr;size_t r_=0,c_=0,next_=0,active_=0,generation_=0;bool stop_=false;void worker(){size_t seen=0;for(;;){std::unique_lock<std::mutex>lk(mu_);cv_.wait(lk,[&]{return stop_||generation_!=seen;});if(stop_)return;seen=generation_;const TensorBinding*w=w_;const float*x=x_;float*y=y_;size_t r=r_,c=c_;lk.unlock();for(;;){size_t i;{std::lock_guard<std::mutex>g(mu_);if(next_>=r)break;i=next_++;}double s=0.0;for(size_t j=0;j<c;j++)s+=(double)elem(*w,i*c+j)*x[j];y[i]=(float)s;}lk.lock();if(--active_==0)done_.notify_one();}}public:MVWorkers(){unsigned n=std::thread::hardware_concurrency();if(n==0)n=1;workers_.reserve(n);for(unsigned k=0;k<n;k++)workers_.emplace_back(&MVWorkers::worker,this);}~MVWorkers(){std::lock_guard<std::mutex>lk(mu_);stop_=true;cv_.notify_all();for(auto&i:workers_)if(i.joinable())i.join();}void run(const TensorBinding&w,const float*x,float*y,size_t r,size_t c){if(r<64){for(size_t i=0;i<r;i++){double s=0;for(size_t j=0;j<c;j++)s+=(double)elem(w,i*c+j)*x[j];y[i]=(float)s;}return;}{std::lock_guard<std::mutex>lk(mu_);w_=&w;x_=x;y_=y;r_=r;c_=c;next_=0;active_=workers_.size();++generation_;}cv_.notify_all();std::unique_lock<std::mutex>lk(mu_);done_.wait(lk,[&]{return active_==0;});}};
static MVWorkers&mv_workers(){static MVWorkers p;return p;}
static void mv(const TensorBinding&w,const float*x,float*y,size_t r,size_t c){mv_workers().run(w,x,y,r,c);}

static void rms(const TensorBinding&w,std::vector<float>&x,float eps){double s=0;for(float z:x)s+=(double)z*z;float k=1.f/std::sqrt((float)(s/x.size())+eps);for(size_t i=0;i<x.size();i++)x[i]*=k*elem(w,i);}
static void rope(float*x,size_t d,size_t pos,float theta){for(size_t i=0;i+1<d;i+=2){float a=pos*std::pow(theta,-2.f*(i/2.f)/d),c=std::cos(a),s=std::sin(a),u=x[i],v=x[i+1];x[i]=u*c-v*s;x[i+1]=u*s+v*c;}}
static int sample(const std::vector<float>&l,const std::vector<int32_t>&hist,Sampling s,std::mt19937_64&r){if(l.empty())return-1;std::vector<std::pair<float,int>>v;v.reserve(l.size());for(size_t i=0;i<l.size();i++){float z=l[i];if(s.repeat_penalty>1)for(auto h:hist)if(h==(int32_t)i){z=z<0?z*s.repeat_penalty:z/s.repeat_penalty;break;}v.push_back({z,(int)i});}if(s.temperature<=0)return std::max_element(v.begin(),v.end())->second;for(auto&a:v)a.first/=s.temperature;std::sort(v.begin(),v.end(),[](auto&a,auto&b){return a.first>b.first;});if(s.top_k>0&&v.size()>(size_t)s.top_k)v.resize(s.top_k);float mx=v[0].first,sum=0;for(auto&a:v){a.first=std::exp(a.first-mx);sum+=a.first;}for(auto&a:v)a.first/=sum;float acc=0;size_t n=v.size();for(size_t i=0;i<v.size();i++){acc+=v[i].first;if(acc>=s.top_p){n=i+1;break;}}std::uniform_real_distribution<float>u(0,1);float total=0;for(size_t i=0;i<n;i++)total+=v[i].first;float q=u(r)*total,c=0;for(size_t i=0;i<n;i++){c+=v[i].first;if(q<=c)return v[i].second;}return v[n-1].second;}

bool KVCache::init(size_t l,size_t h,size_t d,size_t cap){if(!l||!h||!d||!cap||l>SIZE_MAX/(h*d)||l*h*d>SIZE_MAX/cap)return false;size_t n=l*h*d*cap;if(n>SIZE_MAX/(2*sizeof(float)))return false;k_.assign(n,0);v_.assign(n,0);layers_=l;heads_=h;head_dim_=d;capacity_=cap;used_=0;return true;}
void KVCache::clear(){used_=0;std::fill(k_.begin(),k_.end(),0);std::fill(v_.begin(),v_.end(),0);}float*KVCache::key(size_t l,size_t p,size_t h){return k_.data()+((l*capacity_+p)*heads_+h)*head_dim_;}float*KVCache::value(size_t l,size_t p,size_t h){return v_.data()+((l*capacity_+p)*heads_+h)*head_dim_;}

struct TokState{std::unordered_map<std::string,int32_t> id;std::unordered_map<std::string,int> rank;std::unordered_map<std::string,bool> special;std::array<uint8_t,256> dec{};bool gpt2=false;};
static std::unordered_map<const Vocabulary*,TokState> states;
static std::string u8cp(uint32_t cp){std::string s;if(cp<0x80)s.push_back((char)cp);else if(cp<0x800){s.push_back((char)(0xC0|(cp>>6)));s.push_back((char)(0x80|(cp&63)));}else if(cp<0x10000){s.push_back((char)(0xE0|(cp>>12)));s.push_back((char)(0x80|((cp>>6)&63)));s.push_back((char)(0x80|(cp&63)));}else{s.push_back((char)(0xF0|(cp>>18)));s.push_back((char)(0x80|((cp>>12)&63)));s.push_back((char)(0x80|((cp>>6)&63)));s.push_back((char)(0x80|(cp&63)));}return s;}
static std::vector<uint32_t> cps(const std::string&s){std::vector<uint32_t>o;for(size_t i=0;i<s.size();){uint8_t c=(uint8_t)s[i++];if(c<0x80)o.push_back(c);else if((c>>5)==6&&i<s.size())o.push_back(((c&31)<<6)|((uint8_t)s[i++]&63));else if((c>>4)==14&&i+1<s.size())o.push_back(((c&15)<<12)|(((uint8_t)s[i++]&63)<<6)|((uint8_t)s[i++]&63));else if((c>>3)==30&&i+2<s.size())o.push_back(((c&7)<<18)|(((uint8_t)s[i++]&63)<<12)|(((uint8_t)s[i++]&63)<<6)|((uint8_t)s[i++]&63));else o.push_back(0xFFFD);}return o;}
static std::array<std::string,256> byte_enc(){std::array<std::string,256>a;std::vector<int>bs;for(int b=33;b<=126;b++)bs.push_back(b);for(int b=161;b<=172;b++)bs.push_back(b);for(int b=174;b<=255;b++)bs.push_back(b);std::array<bool,256>used{};for(int b:bs)used[b]=true;for(int b=0;b<256;b++)if(!used[b])bs.push_back(b);for(size_t i=0;i<bs.size();i++){int b=bs[i];uint32_t cp=(uint32_t)b;if(i>=189)cp=256+(uint32_t)(i-189);a[b]=u8cp(cp);}return a;}
static std::string byte_decode(const std::string&s){static const auto enc=byte_enc();std::unordered_map<uint32_t,uint8_t>rev;for(int b=0;b<256;b++)for(uint32_t cp:cps(enc[b]))rev[cp]=(uint8_t)b;std::string r;for(uint32_t cp:cps(s)){auto it=rev.find(cp);if(it!=rev.end())r.push_back((char)it->second);else r+=u8cp(cp);}return r;}
static bool is_ascii_letter(uint8_t c){return(c>='A'&&c<='Z')||(c>='a'&&c<='z');}static bool is_digit(uint8_t c){return c>='0'&&c<='9';}static bool is_space(uint8_t c){return c==' '||c=='\t'||c=='\n'||c=='\r'||c=='\f'||c=='\v';}static bool is_punct(uint8_t c){return !is_ascii_letter(c)&&!is_digit(c)&&!is_space(c);}
static std::vector<std::string> smollm_split(const std::string&s){std::vector<std::string>out;size_t p=0,n=s.size();while(p<n){size_t st=p;if(s[p]=='\''&&p+1<n){size_t e=p+1;if((s[e]=='s'||s[e]=='S'||s[e]=='t'||s[e]=='T'||s[e]=='m'||s[e]=='M'||s[e]=='d'||s[e]=='D')&&e+1<=n){out.push_back(s.substr(p,2));p+=2;continue;}if((s[e]=='r'||s[e]=='R'||s[e]=='v'||s[e]=='V'||s[e]=='l'||s[e]=='L')&&e+2<n&&(s[e+1]=='e'||s[e+1]=='E'||s[e+1]=='l'||s[e+1]=='L')){out.push_back(s.substr(p,3));p+=3;continue;}}if(is_space((uint8_t)s[p])){while(p<n&&is_space((uint8_t)s[p]))p++;out.push_back(s.substr(st,p-st));continue;}if(is_digit((uint8_t)s[p])){while(p<n&&is_digit((uint8_t)s[p]))p++;out.push_back(s.substr(st,p-st));continue;}if(is_ascii_letter((uint8_t)s[p])||s[p]>=0x80){while(p<n&&(is_ascii_letter((uint8_t)s[p])||s[p]>=0x80))p++;out.push_back(s.substr(st,p-st));continue;}if(is_punct((uint8_t)s[p])){while(p<n&&is_punct((uint8_t)s[p]))p++;out.push_back(s.substr(st,p-st));continue;}p++;out.push_back(s.substr(st,1));}return out;}
static std::string encode_bytes(const std::string&s){static const auto enc=byte_enc();std::string r;for(unsigned char b:s)r+=enc[b];return r;}static std::vector<std::string> symbols(const std::string&s){std::vector<std::string>v;for(uint32_t cp:cps(s))v.push_back(u8cp(cp));return v;}static std::vector<std::string> bpe(const std::string&s,const TokState&st){auto v=symbols(encode_bytes(s));if(v.empty())return v;for(;;){int best=std::numeric_limits<int>::max();size_t at=v.size();for(size_t i=0;i+1<v.size();i++){auto it=st.rank.find(v[i]+" "+v[i+1]);if(it!=st.rank.end()&&it->second<best){best=it->second;at=i;}}if(at==v.size())break;v[at]+=v[at+1];v.erase(v.begin()+at+1);}return v;}
bool Vocabulary::load(const gguf::Model&m){tokens_.clear();TokState st;auto*v=m.metadata("tokenizer.ggml.tokens");if(!v||!v->is_array())return false;auto*s=m.metadata("tokenizer.ggml.scores");auto*tt=m.metadata("tokenizer.ggml.token_type");tokens_.reserve(v->array.size());for(size_t i=0;i<v->array.size();i++){if(!v->array[i].is_string())return false;Token t{v->array[i].string,0};if(s&&s->is_array()&&i<s->array.size())sf(&s->array[i],t.score);tokens_.push_back(std::move(t));st.id[tokens_.back().text]=(int32_t)i;if(tt&&tt->is_array()&&i<tt->array.size()){uint32_t typ=0;if(tt->array[i].bytes.size()>=4)std::memcpy(&typ,tt->array[i].bytes.data(),4);if(typ==3||typ==4)st.special[tokens_.back().text]=true;}if(tokens_.back().text.size()>4&&tokens_.back().text.rfind("<|",0)==0&&tokens_.back().text.substr(tokens_.back().text.size()-2)=="|>")st.special[tokens_.back().text]=true;}auto*model=m.metadata("tokenizer.ggml.model");st.gpt2=model&&model->is_string()&&model->string=="gpt2";auto*merges=m.metadata("tokenizer.ggml.merges");if(merges&&merges->is_array())for(size_t i=0;i<merges->array.size();i++)if(merges->array[i].is_string()){const auto&q=merges->array[i].string;size_t sp=q.find(' ');if(sp!=std::string::npos&&sp+1<q.size())st.rank[q.substr(0,sp)+" "+q.substr(sp+1)]=(int)i;}states[this]=std::move(st);return!tokens_.empty();}
bool Vocabulary::encode(const std::string&s,std::vector<int32_t>&out)const{out.clear();auto itst=states.find(this);if(itst==states.end())return false;const TokState&st=itst->second;size_t p=0;while(p<s.size()){size_t special_end=std::string::npos;int32_t special_id=-1;if(s[p]=='<'){size_t e=s.find("|>",p+2);if(e!=std::string::npos){e+=2;std::string x=s.substr(p,e-p);auto it=st.id.find(x);if(it!=st.id.end()&&st.special.find(x)!=st.special.end()){special_end=e;special_id=it->second;}}}if(special_end!=std::string::npos){out.push_back(special_id);p=special_end;continue;}size_t next=s.find("<|",p);std::string chunk=(next==std::string::npos?s.substr(p):s.substr(p,next-p));if(chunk.empty()){p=next;continue;}for(const auto&piece:smollm_split(chunk))if(!piece.empty())for(const auto&sym:bpe(piece,st)){auto it=st.id.find(sym);if(it==st.id.end())return false;out.push_back(it->second);}p=(next==std::string::npos?s.size():next);}return!out.empty();}
std::string Vocabulary::decode(int32_t id)const{if(id<0||(size_t)id>=tokens_.size())return{};const std::string&s=tokens_[id].text;if(s.size()>=4&&s.front()=='<'&&s.back()=='>'){if(s.rfind("<|",0)==0&&s.substr(s.size()-2)=="|>")return{};if(s.size()==6&&s[1]=='0'&&s[2]=='x'){auto hex=[](char c)->int{if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return-1;};int a=hex(s[3]),b=hex(s[4]);if(a>=0&&b>=0)return std::string(1,(char)((a<<4)|b));}}return byte_decode(s);}
bool Engine::load(const gguf::Model&m){if(!detect_architecture(m,arch_)||!vocab_.load(m))return false;model_=&m;embedding_=alt(m,"token_embd.weight","model.embed_tokens.weight");output_=alt(m,"output.weight","lm_head.weight");if(!output_.tensor)output_=embedding_;norm_final_=alt(m,"output_norm.weight","model.norm.weight");if(!embedding_.tensor||!norm_final_.tensor)return false;size_t L=arch_.layers;q_.resize(L);k_.resize(L);v_.resize(L);o_.resize(L);norm1_.resize(L);norm2_.resize(L);ffn1_.resize(L);ffn2_.resize(L);ffn3_.resize(L);for(size_t i=0;i<L;i++){std::string n=std::to_string(i);q_[i]=alt(m,"blk."+n+".attn_q.weight","model.layers."+n+".self_attn.q_proj.weight");k_[i]=alt(m,"blk."+n+".attn_k.weight","model.layers."+n+".self_attn.k_proj.weight");v_[i]=alt(m,"blk."+n+".attn_v.weight","model.layers."+n+".self_attn.v_proj.weight");o_[i]=alt(m,"blk."+n+".attn_output.weight","model.layers."+n+".self_attn.o_proj.weight");norm1_[i]=alt(m,"blk."+n+".attn_norm.weight","model.layers."+n+".input_layernorm.weight");norm2_[i]=alt(m,"blk."+n+".ffn_norm.weight","model.layers."+n+".post_attention_layernorm.weight");ffn1_[i]=alt(m,"blk."+n+".ffn_gate.weight","model.layers."+n+".mlp.gate_proj.weight");ffn2_[i]=alt(m,"blk."+n+".ffn_down.weight","model.layers."+n+".mlp.down_proj.weight");ffn3_[i]=alt(m,"blk."+n+".ffn_up.weight","model.layers."+n+".mlp.up_proj.weight");if(!q_[i].tensor||!k_[i].tensor||!v_[i].tensor||!o_[i].tensor||!norm1_[i].tensor||!norm2_[i].tensor||!ffn1_[i].tensor||!ffn2_[i].tensor)return false;}return cache_.init(L,arch_.kv_heads,arch_.hidden/arch_.heads,arch_.context);}
bool Engine::generate(const std::string&prompt,size_t max_tokens,std::vector<std::string>&out){out.clear();if(!model_||!max_tokens)return false;std::vector<int32_t>ids;if(!vocab_.encode(prompt,ids)||ids.empty())return false;bool add_bos=false;if(!bv(model_->metadata("tokenizer.ggml.add_bos_token"),add_bos)){uint32_t dummy=0;if(u32v(model_->metadata("tokenizer.ggml.bos_token_id"),dummy))add_bos=false;}if(add_bos){uint32_t bos=0;if(u32v(model_->metadata("tokenizer.ggml.bos_token_id"),bos)&&bos<vocab_.size())ids.insert(ids.begin(),(int32_t)bos);}cache_.clear();size_t hd=arch_.hidden/arch_.heads;std::vector<float>x(arch_.hidden),z(arch_.hidden),q(arch_.hidden),kk(arch_.kv_heads*hd),vv(arch_.kv_heads*hd),a(arch_.hidden),logits(arch_.vocab);for(size_t pos=0;pos<ids.size()+max_tokens&&pos<arch_.context;pos++){int32_t id=ids[pos];if(id<0||(size_t)id>=vocab_.size())return false;for(size_t i=0;i<arch_.hidden;i++)x[i]=elem(embedding_,(size_t)id*arch_.hidden+i);for(size_t l=0;l<arch_.layers;l++){z=x;rms(norm1_[l],z,arch_.eps);mv(q_[l],z.data(),q.data(),arch_.hidden,arch_.hidden);mv(k_[l],z.data(),kk.data(),arch_.kv_heads*hd,arch_.hidden);mv(v_[l],z.data(),vv.data(),arch_.kv_heads*hd,arch_.hidden);for(size_t h=0;h<arch_.heads;h++)rope(q.data()+h*hd,hd,pos,arch_.rope_theta);for(size_t h=0;h<arch_.kv_heads;h++)rope(kk.data()+h*hd,hd,pos,arch_.rope_theta);for(size_t h=0;h<arch_.kv_heads;h++){std::memcpy(cache_.key(l,pos,h),kk.data()+h*hd,hd*4);std::memcpy(cache_.value(l,pos,h),vv.data()+h*hd,hd*4);}for(size_t h=0;h<arch_.heads;h++){size_t kh=h%arch_.kv_heads;std::vector<float>sc(pos+1);float mx=-std::numeric_limits<float>::infinity();for(size_t pp=0;pp<=pos;pp++){sc[pp]=0;for(size_t j=0;j<hd;j++)sc[pp]+=q[h*hd+j]*cache_.key(l,pp,kh)[j];sc[pp]/=std::sqrt((float)hd);mx=std::max(mx,sc[pp]);}float sm=0;for(float&u:sc){u=std::exp(u-mx);sm+=u;}for(float&u:sc)u/=sm;for(size_t j=0;j<hd;j++){float u=0;for(size_t pp=0;pp<=pos;pp++)u+=sc[pp]*cache_.value(l,pp,kh)[j];a[h*hd+j]=u;}}mv(o_[l],a.data(),z.data(),arch_.hidden,arch_.hidden);for(size_t i=0;i<arch_.hidden;i++)x[i]+=z[i];z=x;rms(norm2_[l],z,arch_.eps);std::vector<float>g(arch_.intermediate),u(arch_.intermediate),d(arch_.hidden);mv(ffn1_[l],z.data(),g.data(),arch_.intermediate,arch_.hidden);if(ffn3_[l].tensor)mv(ffn3_[l],z.data(),u.data(),arch_.intermediate,arch_.hidden);else u=g;for(size_t i=0;i<g.size();i++){float t=g[i];float sig=1.f/(1.f+std::exp(-std::max(-80.f,std::min(80.f,t))));g[i]=(t*sig)*u[i];}mv(ffn2_[l],g.data(),d.data(),arch_.hidden,arch_.intermediate);for(size_t i=0;i<arch_.hidden;i++)x[i]+=d[i];}if(pos+1>=ids.size()){z=x;rms(norm_final_,z,arch_.eps);mv(output_,z.data(),logits.data(),arch_.vocab,arch_.hidden);int next=sample(logits,ids,sampling_,rng_);if(next<0)return false;ids.push_back(next);out.push_back(vocab_.decode(next));if(out.size()>=max_tokens)return true;}}return!out.empty();}
}
