const $=id=>document.getElementById(id);let activeModel='';
const MODE_KEY='piai-inference-mode';
const savedMode=localStorage.getItem(MODE_KEY);if(savedMode&&['cpu','gpu','both'].includes(savedMode))$('inferenceMode').value=savedMode;
$('inferenceMode').onchange=()=>localStorage.setItem(MODE_KEY,$('inferenceMode').value);
async function api(url,opt={}){const r=await fetch(url,opt);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||`HTTP ${r.status}`);return d}
function addMessage(text,who){$('welcome').style.display='none';const row=document.createElement('div');row.className=`message ${who}`;const b=document.createElement('div');b.className='bubble';b.textContent=text;row.appendChild(b);$('chat').appendChild(row);$('chat').scrollTop=$('chat').scrollHeight;return b}
async function loadModels(){try{const d=await api('/api/v1/models');const list=$('modelList');list.innerHTML='';if(!d.models.length){list.innerHTML='<p style="color:#777">No GGUF models installed.</p>';return}d.models.forEach(m=>{const el=document.createElement('div');el.className='model';el.innerHTML=`<strong>${m.name}</strong><small>${m.loaded?'Loaded':'Ready'}</small><br>${m.loaded?'<button class="load">Use</button><button class="unload">Unload</button>':'<button class="load">Load</button>'}`;el.querySelector('button.load').onclick=async()=>{try{await api('/api/v1/models/'+encodeURIComponent(m.name)+'/load',{method:'POST'});activeModel=m.name;$('modelName').textContent=m.name;$('modelsPanel').classList.add('hidden');$('status').textContent='Ready';loadModels()}catch(e){alert(e.message)}};const ub=el.querySelector('button.unload');if(ub)ub.onclick=async()=>{try{await api('/api/v1/models/'+encodeURIComponent(m.name)+'/unload',{method:'POST'});activeModel='';$('modelName').textContent='No model loaded';$('status').textContent='Ready';loadModels()}catch(e){alert(e.message)}};list.appendChild(el)})}catch(e){$('status').textContent='Offline'}}
async function send(){const input=$('prompt'),text=input.value.trim();if(!text)return;if(!activeModel){$('modelsPanel').classList.remove('hidden');return}const mode=$('inferenceMode').value;localStorage.setItem(MODE_KEY,mode);input.value='';input.style.height='auto';$('send').disabled=true;addMessage(text,'user');const bubble=addMessage('','assistant');bubble.classList.add('typing');$('status').textContent=mode==='gpu'?'GPU only…':mode==='both'?'CPU + GPU…':'CPU…';try{const r=await fetch('/api/v1/models/'+encodeURIComponent(activeModel)+'/stream',{method:'POST',headers:{'Content-Type':'application/json','Accept':'text/event-stream','X-PiAI-Inference-Mode':mode},body:JSON.stringify({prompt:text,max_tokens:256,inference_mode:mode})});if(!r.ok){const d=await r.json().catch(()=>({}));throw new Error(d.error||`HTTP ${r.status}`)}const reader=r.body.getReader(),decoder=new TextDecoder();let pending='',done=false,got=false;while(!done){const x=await reader.read();done=x.done;if(x.value)pending+=decoder.decode(x.value,{stream:!done});let parts=pending.split('\n\n');pending=parts.pop()||'';for(const part of parts){const dm=part.split('\n').find(v=>v.startsWith('data: '));if(!dm)continue;const d=JSON.parse(dm.slice(6));if(part.includes('event: token')){bubble.classList.remove('typing');bubble.textContent+=d.token;got=true;$('chat').scrollTop=$('chat').scrollHeight}else if(part.includes('event: error'))throw new Error(d.error||'inference_failed')}}if(!got)bubble.textContent='(empty response)';bubble.classList.remove('typing');$('status').textContent='Ready'}catch(e){bubble.classList.remove('typing');bubble.textContent='Error: '+e.message;$('status').textContent='Inference failed'}$('send').disabled=false;$('chat').scrollTop=$('chat').scrollHeight}
$('composer').onsubmit=e=>{e.preventDefault();send()};$('prompt').oninput=()=>{$('prompt').style.height='auto';$('prompt').style.height=Math.min($('prompt').scrollHeight,140)+'px'};$('modelsBtn').onclick=()=>{$('modelsPanel').classList.remove('hidden');loadModels()};$('closeModels').onclick=()=>$('modelsPanel').classList.add('hidden');$('upload').onchange=async e=>{const f=e.target.files[0];if(!f)return;const fd=new FormData();fd.append('model',f,f.name);$('status').textContent='Uploading…';try{await api('/api/v1/models/upload',{method:'POST',body:fd});$('status').textContent='Ready';loadModels()}catch(err){alert(err.message);$('status').textContent='Ready'}};document.querySelectorAll('[data-prompt]').forEach(b=>b.onclick=()=>{$('prompt').value=b.dataset.prompt;$('prompt').focus()});
api('/api/v1/health').then(()=>{$('status').textContent='Ready';loadModels()}).catch(()=>{$('status').textContent='Offline'});
